### ISSUE TITLE
Settings File not working

### ISSUE THREAD

**Issue by bobster1982** [xMasterX/flipper-pager#2]
Instructions followed on adding custom frequencies. When loading app back up frequencies not found and just the coded frequencies cycle through.

saved as sd/pocsag/settings.txt

# to use manual settings and prevent them from being deleted on upgrade, rename *_user.example files to *_user
Filetype: Flipper SubGhz Setting File
Version: 1

# Add Standard frequencies for your region
#Add_standard_frequencies: true

# Default Frequency: used as default for "Read" and "Read Raw"
#Default_frequency: 433920000

# Frequencies used for "Read", "Read Raw" and "Frequency Analyzer"
#Frequency: 454.0750
#Frequency: 454.2000
#Frequency: 454.6750
#Frequency: 454.7750
#Frequency: 454.8250
#Frequency: 466.0750

# Frequencies used for hopping mode (keep this list small or flipper will miss signal)
#Hopper_frequency: 454.0750
#Hopper_frequency: 454.2000
#Hopper_frequency: 454.6750
#Hopper_frequency: 454.7750
#Hopper_frequency: 454.8250
#Hopper_frequency: 466.0750

# Custom preset
# format for CC1101 "Custom_preset_data:" XX YY XX YY .. 00 00 ZZ ZZ ZZ ZZ ZZ ZZ ZZ ZZ, where: XX-register, YY - register data, 00 00 - end load register, ZZ - 8 byte Pa table register

#Custom_preset_name: AM_1
#Custom_preset_module: CC1101
#Custom_preset_data: 02 0D 03 07 08 32 0B 06 14 00 13 00 12 30 11 32 10 17 18 18 19 18 1D 91 1C 00 1B 07 20 FB 22 11 21 B6 00 00 00 C0 00 00 00 00 00 00

#Custom_preset_name: AM_2
#Custom_preset_module: CC1101
#Custom_preset_data: 02 0D 03 07 08 32 0B 06 14 00 13 00 12 30 11 32 10 17 18 18 19 18 1D 91 1C 00 1B 07 20 FB 22 11 21 B6 00 00 00 C0 00 00 00 00 00 00

**Comment by xMasterX** [comment]
Your frequencies is wrong format and also they are commented with `#`
Config loading is not broken, fix your file
Frequencies should be written in this format `433920000` without any extra symbols
also without `#`

After you figure out issues with your config, custom frequencies can be found at the end of the list, click right button in selector until you find them
