### ISSUE TITLE
flipc.org reporting a build error

### ISSUE THREAD

**Issue by ZL1LAC** [xMasterX/flipper-pager#7]
Just an FYI.

`applications_user/pocsag_pager/pocsag_pager_app.c: In function 'pocsag_pager_app_alloc': applications_user/pocsag_pager/pocsag_pager_app.c:126:5: error: implicit declaration of function 'furi_hal_subghz_enable_ext_power' [-Werror=implicit-function-declaration] 126 | furi_hal_subghz_enable_ext_power(); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ applications_user/pocsag_pager/pocsag_pager_app_i.c: In function 'pcsg_begin': applications_user/pocsag_pager/pocsag_pager_app_i.c:43:24: error: 'furi_hal_subghz' undeclared (first use in this function); did you mean 'furi_hal_subghz_tx'? 43 | furi_hal_gpio_init(furi_hal_subghz.cc1101_g0_pin, GpioModeInput, GpioPullNo, GpioSpeedLow); | ^~~~~~~~~~~~~~~ | furi_hal_subghz_tx applications_user/pocsag_pager/pocsag_pager_app_i.c:43:24: note: each undeclared identifier is reported only once for each function it appears in applications_user/pocsag_pager/pocsag_pager_app_i.c: In function 'pcsg_rx': applications_user/pocsag_pager/pocsag_pager_app_i.c:57:24: error: 'furi_hal_subghz' undeclared (first use in this function); did you mean 'furi_hal_subghz_tx'? 57 | furi_hal_gpio_init(furi_hal_subghz.cc1101_g0_pin, GpioModeInput, GpioPullNo, GpioSpeedLow); | ^~~~~~~~~~~~~~~ | furi_hal_subghz_tx applications_user/pocsag_pager/pocsag_pager_app.c:129:9: error: implicit declaration of function 'furi_hal_subghz_check_radio'; did you mean 'furi_hal_subghz_get_rssi'? [-Werror=implicit-function-declaration] 129 | if(!furi_hal_subghz_check_radio()) { | ^~~~~~~~~~~~~~~~~~~~~~~~~~~ | furi_hal_subghz_get_rssi scons: *** [build/f7-firmware-D/.extapps/pocsag_pager/pocsag_pager_app_i.o] Error 1 applications_user/pocsag_pager/pocsag_pager_app.c:130:9: error: implicit declaration of function 'furi_hal_subghz_select_radio_type'; did you mean 'furi_hal_subghz_set_path'? [-Werror=implicit-function-declaration] 130 | furi_hal_subghz_select_radio_type(SubGhzRadioInternal); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | furi_hal_subghz_set_path applications_user/pocsag_pager/pocsag_pager_app.c:130:43: error: 'SubGhzRadioInternal' undeclared (first use in this function); did you mean 'SubGhzRadioPreset'? 130 | furi_hal_subghz_select_radio_type(SubGhzRadioInternal); | ^~~~~~~~~~~~~~~~~~~ | SubGhzRadioPreset applications_user/pocsag_pager/pocsag_pager_app.c:130:43: note: each undeclared identifier is reported only once for each function it appears in applications_user/pocsag_pager/pocsag_pager_app.c:131:9: error: implicit declaration of function 'furi_hal_subghz_init_radio_type'; did you mean 'furi_hal_subghz_set_path'? [-Werror=implicit-function-declaration] 131 | furi_hal_subghz_init_radio_type(SubGhzRadioInternal); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | furi_hal_subghz_set_path applications_user/pocsag_pager/pocsag_pager_app.c: In function 'pocsag_pager_app_free': applications_user/pocsag_pager/pocsag_pager_app.c:148:5: error: implicit declaration of function 'furi_hal_subghz_disable_ext_power' [-Werror=implicit-function-declaration] 148 | furi_hal_subghz_disable_ext_power(); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ applications_user/pocsag_pager/pocsag_pager_app.c:150:37: error: 'SubGhzRadioInternal' undeclared (first use in this function); did you mean 'SubGhzRadioPreset'? 150 | furi_hal_subghz_init_radio_type(SubGhzRadioInternal); | ^~~~~~~~~~~~~~~~~~~ | SubGhzRadioPreset cc1: all warnings being treated as errors scons: *** [build/f7-firmware-D/.extapps/pocsag_pager/pocsag_pager_app.o] Error 1 applications_user/pocsag_pager/views/pocsag_pager_receiver.c: In function 'pcsg_view_receiver_draw': applications_user/pocsag_pager/views/pocsag_pager_receiver.c:210:23: error: implicit declaration of function 'furi_hal_subghz_get_radio_type'; did you mean 'furi_hal_subghz_get_rssi'? [-Werror=implicit-function-declaration] 210 | bool ext_module = furi_hal_subghz_get_radio_type(); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | furi_hal_subghz_get_rssi cc1: all warnings being treated as errors scons: *** [build/f7-firmware-D/.extapps/pocsag_pager/views/pocsag_pager_receiver.o] Error 1`

**Comment by xMasterX** [comment]
Follow this instruction:
https://github.com/xMasterX/flipper-pager/releases/tag/v1.2

Don't use flipc
